//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrismProject.Source.System2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Assets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Assets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrismProject.Source.System2.Assets", typeof(Assets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Arrow {
            get {
                object obj = ResourceManager.GetObject("Arrow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Boot {
            get {
                object obj = ResourceManager.GetObject("Boot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz:;&quot;&apos;&lt;,&gt;.?/!@#$%^&amp;*()_+-=`~.
        /// </summary>
        internal static string CharSet {
            get {
                return ResourceManager.GetString("CharSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAAOABEAEQAQgBCAEIAQgBEAEQAOAAAAAAAAAAAAAAAAAAwAFAAEAAQABAAEAAQABAAEAAQAAAAAAAAAAAAAAAAADgARABCAEIABAAIABgAMAAgAH4AAAAAAAAAAAAAAAAAPABEAEIABAAYAAYAQgBCAEYAPAAAAAAAAAAAAAAAAAAEAAwADAAUACQAZABEAP8ABAAEAAAAAAAAAAAAAAAAAH4AQABAAEAAfAACAAIAQgBiADwAAAAAAAAAAAAAAAAACAAIABAAMAA8AEYAQgBCAEYAPAAAAAAAAAAAAAAAAAB+AAQABAAMAAgAGAAQABAAIAAgAAAAAAAAAAAAAAAAADgAJABEACQAOABGAEIAQgBGADwAAAAAAAAAAAAAAAAAOABEAEIAQgBEADwACAAQABAAIAAAAAAAAAAAAAAAAAAIAAwAFAAUACIAIgBhAH8AQYCAgAAAAAAAAAAAAAAAAH4AQwBBAEIAfgBBAEEAQQBBAH4AAAAAAAAAAAAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Comfortaa {
            get {
                return ResourceManager.GetString("Comfortaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfortaa.
        /// </summary>
        internal static string ComfortaaName {
            get {
                return ResourceManager.GetString("ComfortaaName", resourceCulture);
            }
        }
    }
}
