//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrismProject.Source.System2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Theme {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Theme() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrismProject.Source.System2.Theme", typeof(Theme).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255, 69, 69, 69.
        /// </summary>
        internal static string ProgressBarBackground {
            get {
                return ResourceManager.GetString("ProgressBarBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255, 255, 255, 255.
        /// </summary>
        internal static string ProgressBarForeground {
            get {
                return ResourceManager.GetString("ProgressBarForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255, 0, 255, 0.
        /// </summary>
        internal static string SolidBackground {
            get {
                return ResourceManager.GetString("SolidBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255, 25, 25, 25.
        /// </summary>
        internal static string WindowBar {
            get {
                return ResourceManager.GetString("WindowBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255, 255, 255, 255.
        /// </summary>
        internal static string WindowPage {
            get {
                return ResourceManager.GetString("WindowPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255, 0, 0, 0.
        /// </summary>
        internal static string WindowShadow {
            get {
                return ResourceManager.GetString("WindowShadow", resourceCulture);
            }
        }
    }
}
